= Installation
:toc: left
:toclevels: 3
:icons: font

:source-highlighter: coderay
:source-language: YAML

===== xref:../README.adoc[🏠 Return to the index]

== Initial Setup

* https://www.spigotmc.org/resources/13932/[Download the plugin]
* Put "FastAsyncWorldEdit.jar" into your `plugins` folder
* Reboot the server and FAWE will generate all necessary files.

[WARNING]
Make sure your server has been launched with https://adoptium.net/[Java 17].

[WARNING]
Do not install WorldEdit! FAWE is a <ins>direct</ins> replacement.

[TIP]
If you are looking to install FastAsyncVoxelSniper too, https://github.com/IntellectualSites/FastAsyncVoxelSniper[go to this repo].

== Third Party Plugin Support

=== Region Restrictions
The following plugins are supported:

* PlotSquared
* WorldGuard

Deprecated plugin support:

* Towny
* GriefPrevention
* FactionsUUID

[TIP]
This can be disabled in the config or bypassed with the `/wea` command or the `fawe.bypass` permission.

== Logging and Rollback

Enable `use-disk` and `use-database` in the `config.yml` to use the in built FAWE logging/rollback.

[TIP]
It is safe to give normal players access to FAWE rollback. To bypass logging use `//fast`.